{% set name = "ntm-profiler" %}
{% set version = "0.2.2" %}
{% set sha256 = "387e3e6315e7d9165eeb2ea03e98c7128ccd68631d3c24b187361c96eb331d47" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/NTM-Profiler/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - python>=3.7
    - pip
    - gatk4
    - samtools=1.10
    - bwa
    - snpeff=5.0
  run:
    - python>=3.7
    - kmc=3.2.1
    - mash=2.3
    - pathogen-profiler=2.0.0


test:
  imports:
    - ntm_profiler

  commands:
    - ntm-profiler -h

about:
  home: https://github.com/jodyphelan/NTM-Profiler
  license: GPL3
  license_file: LICENSE
  summary: Profiling tool for NTM to detect species and resistance from WGS data
