package:
  name: fwdpy11
  version: "0.19.0"

source:
  url: https://files.pythonhosted.org/packages/81/25/c7abd5cd81512e3cf543ce969e2730c30254460c30d0e1bba2dc6705497f/fwdpy11-0.19.0.tar.gz
  sha256: 8125c12fff395b1932b174b33212e4d672e6693c8782f4bd64e0b3905789b272

build:
  skip: True # [py27 or py<37]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pkgconfig
    - python
    - pip
    - numpy >=1.20
    - pybind11 ==2.9.1
    - tskit >=0.5
    - gsl
    - openblas
    - attrs
    - setuptools_scm
  run:
    - python
    - numpy >=1.20
    - tskit >=0.5
    - gsl
    - openblas
    - scipy
    - attrs
    - black
    - demes >=0.2
    - intervaltree

test:
  # Python imports
  imports:
    - fwdpy11

about:
  home: http://pypi.python.org/pypi/fwdpy11
  license: GNU General Public License v3 or later (GPLv3+)
  license_file: "COPYING"
  summary: 'Forward-time population genetic simulation in Python.'

extras:
  identifiers:
    - 10.1534/genetics.114.165019
    - 10.1371/journal.pcbi.1006581
