{% set name = "mhcnuggets" %}
{% set version = "2.4.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://files.pythonhosted.org/packages/c9/48/980b9e3633764aadd898f3fac87816d76a1b394327a6e39bf180cd91a590/mhcnuggets-2.4.0.tar.gz
  sha256: '7e25b01df4b4a870aa8d8e938a506e10522c8c2716f6f87292b5ac7a8a175822'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - numpy>=1.16.1
    - scipy
    - scikit-learn
    - tensorflow=1.13.1
    - keras
  run:
    - python
    - numpy>=1.16.1
    - scipy
    - scikit-learn
    - tensorflow=1.13.1
    - keras

test:
  imports:
    - mhcnuggets
    - mhcnuggets.data
    - mhcnuggets.data.production
    - mhcnuggets.data.production.mhcI
    - mhcnuggets.data.production.mhcII
    - mhcnuggets.data.test
    - mhcnuggets.saves
    - mhcnuggets.saves.production
    - mhcnuggets.saves.test
    - mhcnuggets.src

about:
  home: http://karchinlab.org/apps/mhcnuggets.html
  license: Apache License
  license_family: APACHE
  summary: 'MHCnuggets: Neoantigen peptide MHC binding prediction for class I and II'
  description: "# MHCnuggets\n\nWelcome to MHCnuggets! Presumably you're here to do some\npeptide-MHC prediction and not because you were [hungry](https://www.mcdonalds.com/us/en-us/product/chicken-mcnuggets-4-piece.html).\n\
    \n### Usage ###\nFor an overview of how to use MHCnuggets please refer to the Jupyter notebook\ncalled `user_guide.ipynb` in the repository\n\n### Installation ###\n\nMHCnuggets is `pip` installable\
    \ as:\n```bash\npip install mhcnuggets\n```\n\n**Required pacakges:**\n\n* numpy\n* scipy\n* scikit-learn\n* tensorflow\n* keras\n\nYou might want to check if the Keras backend is configured to use\n\
    the Tensforflow backend."
