{% set version = "3.0.1" %}
{% set bioconda_version = "3.0.1" %}
{% set vdb_version = "3.0.1" %}
{% set ngs_version = "3.0.1" %}

package:
  name: sra-tools
  version: '{{ bioconda_version }}'

source:
  - url: https://github.com/ncbi/sra-tools/archive/{{version}}.tar.gz
    sha256: 49cf89855c98d96e418f7e55cab277db30dd756e14a66731bd11770683974c80
    folder: sra-tools
  - url: https://github.com/ncbi/ncbi-vdb/archive/{{vdb_version}}.tar.gz
    sha256: d72a59ba0a837692a148fae7bdc7ebb441ba22d77c674471d378f43808d9dea1
    folder: ncbi-vdb

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - flex
    - bison
  host:
    - ncbi-ngs-sdk
    - libxml2
    - zlib
    - bzip2
    - hdf5
    - perl
  run:
    - ca-certificates
    - ossuuid
    - perl
    - ncbi-ngs-sdk
    - perl-xml-libxml
    - perl-uri
    - curl

test:
  commands:
    # create config file with /LIBS/GUID value so tests pass; new GUID value will be created in user's home dir upon installation via post-link.sh
    - if ! grep "/LIBS/GUID" ~/.ncbi/user-settings.mkfg &> /dev/null; then mkdir -p ~/.ncbi && printf '/LIBS/GUID = "%s"\n' `uuid` > ~/.ncbi/user-settings.mkfg; fi
    - fastq-dump --help > /dev/null
    - prefetch --help > /dev/null
    - sam-dump --help > /dev/null
    - sra-pileup --help > /dev/null
    - vdb-config --help > /dev/null
    - vdb-decrypt --help > /dev/null
    - fastq-dump -N 1 -X 1 SRR000001 && grep '@SRR000001.1' SRR000001.fastq
    - fasterq-dump --help > /dev/null

about:
  home: https://github.com/ncbi/sra-tools
  license: Public Domain
  summary: SRA Toolkit and SDK from NCBI
  description:  |
    The SRA Toolkit and SDK from NCBI is a collection of tools and libraries
    for using data in the INSDC Sequence Read Archives.

extra:
  notes: 'After installation, you should run the configuration tool: ./vdb-config
    -i. This tool will setup your download/cache area for downloaded files and references.'
