{% set name = "sashimi.py" %}
{% set version = "0.0.8" %}


package:
  name: sashimi-py
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 22d444d3ae5416ddaab3a20d2fa7e254edc00bbf22165edfdea22d328852dd43

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - wheel
    - setuptools
    - setuptools_scm
    - pip
    - filetype
    - pysam
    - pybigwig
    - hicmatrix
    - click-option-group
  run:
    - python
    - wheel
    - pysam
    - filetype
    - pybigwig
    - click-option-group
    - cairocffi
    - hicmatrix
    - samtools
    - tabix
    - matplotlib-base
    - seaborn-base
    - click
    - numpy
    - requests
    - xmltodict
    - pandas
    - loguru

test:
  imports:
    - sashimi

  commands:
    - sashimipy --help

about:
  home: https://github.com/ygidtu/sashimi.py
  summary: "This is an pure Python version of sashimi plot"
  doc_url: https://sashimi.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ygidtu
